rem catch-up for June
echo Note: if the script seems to freeze, just press space-bar or enter to continue (silent message "Press any key to continue")
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220601.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220601-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220602.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220602-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220603.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220603-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220604.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220604-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220605.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220605-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220606.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220606-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220607.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220607-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220608.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220608-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220609.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220609-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220610.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220610-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220611.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220611-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220612.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220612-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220613.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220613-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220614.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220614-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220615.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220615-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220616.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220616-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220617.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220617-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220618.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220618-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220619.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220619-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220620.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220620-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220621.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220621-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220622.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220622-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220623.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220623-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220624.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220624-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220625.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220625-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220626.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220626-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220627.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220627-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220628.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220628-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220629.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220629-SlowPages.txt"
logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220630.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220630-SlowPages.txt"
rem logparser.exe "SELECT TOP 100 time-taken, cs-uri-stem FROM d:\inetpub\logs\logfiles\W3SVC1\u_ex220631.log ORDER BY time-taken DESC" -i:iisw3c -o:tsv > "u_ex220631-SlowPages.txt"
pause