-- rename the table, so we can replace it
RENAME TABLE MIPSTIM.SELFPAYMSG TO tbSelfPayMessage_bad FOR SYSTEM NAME SPM_BAD;

-- drop the PK constraint so we can create a new one of those too (without a name collision)
ALTER TABLE MIPSTIM.SPM_BAD DROP CONSTRAINT MIPSTIM.PK_tbSelfPayMessage;
-- also drop any FKs at this time


-- create the replacement table
CREATE TABLE MIPSTIM.SELFPAYMSG --tbSelfPayMessage 
( 
	slpID INTEGER GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE NO CYCLE NO ORDER CACHE 20 ), 

	slpCode FOR COLUMN SLFPAYCODE CHAR(2) CCSID 37 NOT NULL DEFAULT ' ',
	slpDescription FOR COLUMN SLFPAYDESC CHAR(255) CCSID 37 NOT NULL DEFAULT ' ',
	slpEndDate FOR COLUMN ENDDATE CHAR(10) CCSID 37 NOT NULL DEFAULT '1900-01-01', 
	slpModifiedDate FOR COLUMN MODIFIEDDT CHAR(10) CCSID 37 NOT NULL DEFAULT '1900-01-01', 
	slpModifiedBy_usrID FOR COLUMN MODIFIEDBY INTEGER NOT NULL DEFAULT 0, 
	slpActive FOR COLUMN ACTIVE CHAR(1) NOT NULL DEFAULT ' ', 
	slpBeginDate FOR COLUMN BEGINDATE CHAR(10) CCSID 37 NOT NULL DEFAULT '1900-01-01', 
	CONSTRAINT MIPSTIM.PK_tbSelfPayMessage PRIMARY KEY( slpID )
);

-- Setting label text for tbSelfPayMessage 
LABEL ON TABLE MIPSTIM.SELFPAYMSG IS 'tbSelfPayMessage' ;

-- Setting table (Long) name for tbSelfPayMessage (SELFPAYMSG) 
RENAME TABLE MIPSTIM.SELFPAYMSG TO tbSelfPayMessage FOR SYSTEM NAME SELFPAYMSG;

------------------------------------------------------------
-- Now you need to turn journaling on for the table. 
-- I still haven't figured out how to do that in SQL yet.
-- So, go into iSeries Navigator and do it manually.
-- 
-- if journaling isn't on (for a new table), you can't add data to it
-- ...then continue
------------------------------------------------------------

--copy the data from the old table to the new table
INSERT INTO MIPSTIM.SELFPAYMSG OVERRIDING SYSTEM VALUE
SELECT slpID, LEFT(slpCode,2) AS slpCode, slpDescription, slpEndDate, slpModifiedDate, slpModifiedBy_usrID, slpActive, slpBeginDate 
FROM MIPSTIM.SPM_BAD;

-- drop the old table
DROP TABLE MIPSTIM.tbSelfPayMessage_bad;

--maybe reapply any foreign keys that we had to drop


--make sure any locks on this table are lifted
commit;
